# yaml-language-server: $schema=https://platen.io/schemas/config/schema.json
# Update to your own settings for URL/title
baseURL: https://phantom-funeral-too.netlify.app/
title:   Phantom Funeral Press 202X

module:
  imports:
    - path: github.com/platenio/platen/modules/platen

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true

menu:
  before:
    - name: Blog
      url: /posts
      weight: 10
  after:
    - name: Platen Documentation
      url: https://platen.io/
      weight: 10

params:
  description: Ephemerality by the Phantom Funeral Press.
